name: Actions Runner Controller Demo
on:
  workflow_dispatch:

jobs:
  Explore-GitHub-Actions:
    # You need to use the INSTALLATION_NAME from the previous step
    runs-on: github-arc-runner-test
    steps:
    - run: echo "🎉 This job uses runner scale set runners!"
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'
    - name: Compile Hello World
      run: go build -o hw test.go
    - name: Run Hello World
      run: ./hw